
INSERT INTO CUSTOMER (CUSTOMER_NAME,CUSTOMER_EMAIL,CUSTOMER_MOBILE,ADDRESS1,ADDRESS2,ACCOUNT_TYPE) VALUES ('TEST USER1','testemail1@gmail.com','639260000001','156 brgy. Balite Malolos','#1 tower 2 manila building','S');
INSERT INTO CUSTOMER (CUSTOMER_NAME,CUSTOMER_EMAIL,CUSTOMER_MOBILE,ADDRESS1,ADDRESS2,ACCOUNT_TYPE) VALUES ('TEST USER2','testemail2@gmail.com','639260000002','1 brgy. Balite Malolos','#2 tower 2 manila building','C');


INSERT INTO ACCOUNT (CUSTOMER_NUMBER,ACCOUNT_TYPE,AVAILABLE_BALANCE) VALUES (1,'S',20000.25);
INSERT INTO ACCOUNT (CUSTOMER_NUMBER,ACCOUNT_TYPE,AVAILABLE_BALANCE) VALUES (1,'S',20520.00);
INSERT INTO ACCOUNT (CUSTOMER_NUMBER,ACCOUNT_TYPE,AVAILABLE_BALANCE) VALUES (2,'C',10000.15);