DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS ACCOUNT;
CREATE TABLE CUSTOMER(
   CUSTOMER_NUMBER bigint auto_increment PRIMARY KEY,
   CUSTOMER_NAME VARCHAR(50),
   CUSTOMER_MOBILE VARCHAR(20),
   CUSTOMER_EMAIL VARCHAR(50),
   ADDRESS1 VARCHAR(100),
   ADDRESS2 VARCHAR(100),
   ACCOUNT_TYPE VARCHAR(10)
);
CREATE TABLE ACCOUNT(
   ACCOUNT_NUMBER bigint auto_increment PRIMARY KEY,
   CUSTOMER_NUMBER VARCHAR(50),
   ACCOUNT_TYPE CHARACTER,
   AVAILABLE_BALANCE NUMERIC(20, 2)
);

CREATE INDEX idx_customer_name
ON CUSTOMER(customer_name);

CREATE INDEX idx_account_number
ON ACCOUNT(account_number);

CREATE INDEX idx_account_type
ON ACCOUNT(account_type);
